[package]
name = "2048"
version = "0.1.0"
authors = ["Swiip <matthieu.lux@gmail.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[profile.release]
opt-level = "s"
